---
name: Install

"on":
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          make install
      - run: |
          make test
