---
name: Install

"on":
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  install_neat:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04]
        shell: [bash, zsh, ksh]
        tool: [curl]
    steps:
      - run: |
          sudo apt-get update -y -qq
          sudo apt-get install -qq -y ${{ matrix.tool }} ${{ matrix.shell }}
      - run: |
          ${{ matrix.tool }} -sSL \
            https://raw.githubusercontent.com/kornicameister/docker-compose-extra/${{ github.ref }}/install.sh \
            | sudo ${{ matrix.shell }} /dev/stdin
        if: github.event_name == 'pull_request'
      - run: |
          ${{ matrix.tool }}  -sSL https://git.io/JfZEY | sudo ${{ matrix.shell }} /dev/stdin
        if: github.event_name == 'push'
  install_make:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          sudo make install
